### ISSUE TITLE
"Exceptiong calling 'Add' with '2' arguments"

### ISSUE THREAD

**Issue by vlad-fp** [vors/ZLocation#73] opened 2018-10-17 12:44 UTC
```
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: ''  Key being added: ''"
At ...\WindowsPowerShell\Modules\ZLocation\1.0.0\ZLocation.Storage.psm1:12 char:9
+         $hash.add($item.path, $item.weight)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```
ZLocation worked great until this happened. What can I do?

**Comment by vors** [comment] 2018-10-19 00:48
This is fixed in 1.1.0 (dupe of #61)

**Closed by vors** 2018-10-19 00:48 UTC
