### ISSUE TITLE
all known locations cleared on update

### ISSUE THREAD

**Issue by kelbyers** [vors/ZLocation#54] opened 2018-09-03 15:56 UTC
There was no warning in the documentation that all my saved locations would be gone after updating from version 0.1.0 to version 0.3.0.

Immediately prior to update, my shell showed:
```
[ZLocation] knows about 57 locations.
```

After updating and starting a new shell, I see this:
```
[ZLocation] knows about 0 locations.
```

**Comment by kelbyers** [comment] 2018-09-03 15:59
Huh. After closing all my powershell windows and launching a new powershell window, all my locations are there, but tab completion does not work any longer.

**Comment by cspotcode** [comment] 2018-09-04 18:51
We'll be publishing a new version very shortly that may fix the tab completion issue.  But first we need to add tests that an automatic migration will work, so you won't lose your saved locations.

In the meantime, are you using any aliases to zlocation?  What is the command line when you press "tab"?  What version & edition of PowerShell are you using?

**Comment by kelbyers** [comment] 2018-09-05 03:07
I'm on a Windows 10 Home system. My version is:
```
~> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  228
```

I'm not using any aliases for ZLocation. I simply have these lines in my profile:
```
Import-Module ZLocation
Write-Host -Foreground Green "`n[ZLocation] knows about $((Get-ZLocation).Keys.Count) locations.`n"
```

Just before upgrading from 0.1.0 to 0.3.0, I was able to type `z librs` and then `<Tab>` and it gave a choice between `C:\Users\kel\git\librsync\librsync` and `C:\Users\kel\go\src\github.com\kelbyers\librsync-go`.

After upgrading, `z librs` followed by `<Tab>` results in nothing happening at all. Both of those directories are in the results of `(Get-ZLocation).Keys`:

```
~> (Get-ZLocation).Keys | select-string librs

C:\Users\kel\go\src\github.com\kelbyers\librsync-go\vendor\github.com\resin-os\circbuf
C:\Users\kel\go\src\github.com\kelbyers\librsync-go\vendor\github.com
C:\Users\kel\go\src\github.com\kelbyers\librsync-go
C:\Users\kel\go\src\github.com\resin-os\librsync-go\cmd\rdiff
C:\Users\kel\git\librsync\librsync
C:\Users\kel\go\src\github.com\resin-os\librsync-go\cmd
```

**Comment by vors** [comment] 2018-09-07 03:36
Thank you for the report! I think it should be fixed very with the next release. Closing as duplicate of #49

**Closed by vors** 2018-09-07 03:36 UTC
